config/routes.rb
Rails.application.routes.draw do
  root 'items#index'

  resources :items, only: [:index, :show]
  resources :file_import_sessions, only: [:index, :show]
  match 'search'              => 'search#index',        :controller => 'search',  :via => :get
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# encoding: utf-8

class Category < ApplicationRecord

    validates :name, presence: true

    has_many :items

end

app/models/file_import_log_entry.rb
# encoding: utf-8
class FileImportLogEntry < ApplicationRecord

    validates :line_number, presence: true, numericality: {only_integer: true, greater_than: 0}
    validates :warning, presence: true
    validates :line_content, presence: true 

    belongs_to :file_import_session

end

app/models/file_import_session.rb
# encoding: utf-8
class FileImportSession < ApplicationRecord

    validates :file_name, presence: true

    has_many :file_import_log_entries

end

app/models/item.rb
# encoding: utf-8

class Item < ApplicationRecord

    validates :title, presence: true
    validates :summary, presence: true
    validates :bates_number, presence: true, format: { with: /[a-z]{3}\d*\-[a-zA-z]{3}\d*/i } # e.g.: ABC000-XYZ123456
    validates :page_count, presence: true,
                           numericality: {
                               only_integer: true,
                               greater_than: 0
                           }
    
    belongs_to :category

    searchable auto_index: true do
        text :title
        text :summary
    end

    class << self
        def with_category(category)
            where(category_id: category.id)
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/file_import_sessions_controller.rb
class FileImportSessionsController < ApplicationController
  def index
    @file_import_sessions = FileImportSession.order(created_at: :desc).paginate(page: params[:page])
  end

  def show
    @file_import_session = FileImportSession.find(params[:id])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    category = Category.find_by_id(params[:category_id])
    @items = if category
                Item.with_category(category).paginate(page: params[:page])
             else
                Item.paginate(page: params[:page])
             end
  end

  def show
    @item = Item.find params[:id]
  end
end

app/controllers/search_controller.rb
# encoding: utf-8
class SearchController < ApplicationController
  
  def index
    unless params[:q].blank?
      @search_result = Sunspot.search Item do
        fulltext params[:q]
        paginate(:page => params[:page], :per_page => 30)
      end
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/file_import_sessions_helper.rb
module FileImportSessionsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/file_import_sessions/index.html.erb
<div class="card">
    <div class="card-header">
        <i class="fa fa-align-justify"></i> <%= FileImportSession.model_name.human.pluralize%> 
    </div>
    <div class="card-body">
        <table class="table table-responsive-sm table-striped">
            <thead>
                <tr>
                    <th><%= t 'activerecord.attributes.file_import_session.file_name'%></th>
                    <th><%= t 'activerecord.attributes.file_import_session.created_at'%></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <% cache(@file_import_sessions) do%>
                    <% @file_import_sessions.each do |file_import_session| %>
                    <tr title="<%= file_import_session.file_name%>">
                        <td><%= file_import_session.file_name%></td>
                        <td><%= l(file_import_session.created_at, format: :long)%></td>
                        
                        <td align="right">
                            <%= link_to file_import_session_path(file_import_session), class: "btn btn-outline-warning" do %> 
                                <i class="fa fa-eye"></i>
                            <% end %>
                        </td>
                    </tr>
                    <% end %>
                <% end %>
            </tbody>
        </table>
        <%= will_paginate @file_import_session %>
    </div>
</div>

app/views/file_import_sessions/show.html.erb
<div class="card">
    <div class="card-header">
        <%= FileImportSession.model_name.human %>: <strong><%= @file_import_session.file_name%> - <%= l @file_import_session.created_at, format: :long%></strong>
    </div>
    <div class="card-body">
        <p><%= t('file_import_sessions.show.warnings', warnings: @file_import_session.file_import_log_entries.count)%> </p>

        <table class="table table-responsive-sm table-striped">
            <thead>
                <tr>
                    <th><%= t 'activerecord.attributes.file_import_log_entry.line_number'%></th>
                    <th><%= t 'activerecord.attributes.file_import_log_entry.warning'%></th>
                    <th><%= t 'activerecord.attributes.file_import_log_entry.line_content'%></th>
                </tr>
            </thead>
            <tbody>
                <% cache(@file_import_session.file_import_log_entries) do%>
                    <% @file_import_session.file_import_log_entries.each do |log| %>
                    <tr>
                        <td><%= log.line_number%></td>
                        <td><%= log.warning%></td>
                        <td><%= log.line_content%></td>
                    </tr>
                    <% end %>
                <% end %>
            </tbody>
        </table>
    </div>
    <div class="card-footer">
      <%= link_to t('general.close'), file_import_sessions_path, class: "btn btn-danger"%>
    </div>
</div>

app/views/items/index.html.erb
<div class="card">
    <div class="card-header">
        <i class="fa fa-align-justify"></i> <%= Item.model_name.human.pluralize%> 
        <%= select_tag :category_id, options_from_collection_for_select(Category.all, :id, :name, params[:category_id]), prompt: I18n.t('general.select_category') %>
    </div>
    <div class="card-body">
        <table class="table table-responsive-sm table-striped">
            <thead>
                <tr>
                    <th><%= t 'activerecord.attributes.item.title'%></th>
                    <th><%= t 'activerecord.attributes.item.bates_number'%></th>
                    <th><%= t 'activerecord.attributes.item.category'%></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <% cache(@items) do%>
                    <% @items.each do |item| %>
                    <tr title="<%= item.title%>">
                        <td><%= item.title%></td>
                        <td><%= item.bates_number%></td>
                        <td><%= item.category.name%></td>
                        
                        <td align="right">
                            <%= link_to item_path(item), class: "btn btn-outline-warning" do %> 
                                <i class="fa fa-eye"></i>
                            <% end %>
                        </td>
                    </tr>
                    <% end %>
                <% end %>
            </tbody>
        </table>
        <%= will_paginate @items %>
    </div>
</div>

app/views/items/show.html.erb
<div class="card">
    <div class="card-header">
        <%= Item.model_name.human %>: <strong><%= @item.bates_number%></strong>
    </div>
    <div class="card-body">
        <p class="card-title"><strong><%= @item.category.name%></strong></p>
        <p class="card-text"><%= t('activerecord.attributes.item.summary')%>: <%= @item.summary %></p>
    </div>
    <div class="card-footer">
      <%= link_to t('general.close'), items_path, class: "btn btn-danger"%>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Integreon" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>
    

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'Integreon', root_path, class: 'navbar-brand'%>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to t('menu.options.items'), items_path   %></li>
            <li><%= link_to t('menu.options.search'), search_path   %></li>
            <li><%= link_to t('menu.options.import_sessions'), file_import_sessions_path   %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-10">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Integreon 2019</p>
      </footer>
    </div> <!-- /container -->

  </body>
</html>
<%= javascript_include_tag "application" %>

app/views/search/index.html.erb
 <%= form_tag search_path, method: :get, class: "navbar-form-custom", role: "search" do %>
    <div class="form-group">
    <%= text_field_tag :q, nil, class: 'form-control', placeholder: t('general.search') %>
    </div>
<% end %>
<% unless @search_result.blank? %>
<div class="col-lg-12">
    <div class="card">
        <div class="card-header">
            <i class="fa fa-align-justify"></i> <%= t('search.results_summary', total: @search_result.total, query: params[:q]).html_safe%>
        </div>
        <div class="card-body">
          <% @search_result.results.each do |item| %>
            <div class="hr-line-dashed"></div>
            <div class="search-result">
                <h3><%= link_to item.title, item_path(item), class:'search-link' %></h3>
                <p>
                    <%= item.summary %>
                </p>
            </div>
          <% end %>
          <%= will_paginate @search_result.hits%>
        </div>
    </div>
</div>
<% end %>